# Linear algebra
dov-summer school 2019, peter.gruber@usi.ch

## A quick intro to numpy arrays
Create the following vectors and matrics
$$u=\begin{pmatrix}4\\5\\6\end{pmatrix} \quad x=\begin{pmatrix}1\\2\\3\end{pmatrix} \quad y=\begin{pmatrix}1&2&3\end{pmatrix} \quad A=\begin{pmatrix}1&2&3\\4&5&6\\7&8&9\end{pmatrix} \quad B=\begin{pmatrix}2&2&4\\1&3&5\\2&4&8\end{pmatrix}$$

In [9]:
# Python Code goes here
import numpy as np
u = np.array( [[4],[5],[6]] )
x = np.transpose( np.array([[1,2,3]]) )
y = np.array([1,2,3])
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[2,2,4],[1,3,5],[2,4,8]])
print(u)
print(x)
print(y)
print(A)
print(B)

[[4]
 [5]
 [6]]
[1 2 3]
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 4]
 [1 3 5]
 [2 4 8]]


### Subsetting and slicing arrays
* Pretty much like lists: index starts at 0
* Careful: column vectors need 2 indices
* Entire rows (columns): leave out column (row) index or replace by ":"

In [10]:
print(y[0])
print(u[1])
print(u[1][0])
print(A[2,1])
print(A[1,])
print(A[1,:])

1
[5]
5
8
[4 5 6]
[4 5 6]


In [11]:
# Careful about this one
print(A[1:])

[[4 5 6]
 [7 8 9]]


### Expected operations

In [12]:
print(y+1)
print(2*y)
print(u+x)
print(A-B)

[2 3 4]
[2 4 6]
[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[-1  0 -1]
 [ 3  2  1]
 [ 5  4  1]]


### Unexpected operations

In [14]:
print(u+y)
print(np.transpose(x)*x)
print(A*B)
print(A**2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[1 4 9]
[[ 2  4 12]
 [ 4 15 30]
 [14 32 72]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### Matrix algebra in Python

In [15]:
print(A.dot(B))       # A * B
print(A.dot(x))       # A * x
print(y.dot(A))       # y * A
print(y.dot(x))       # y * x

[[ 10  20  38]
 [ 25  47  89]
 [ 40  74 140]]
[14 32 50]
[30 36 42]
14


In [16]:
Binv = np.linalg.inv(B)
print(Binv)
print(B.dot(Binv))

[[ 1.   0.  -0.5]
 [ 0.5  2.  -1.5]
 [-0.5 -1.   1. ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### A few important vector/matrix operations
L-p norms are defined as
$$\big(\sum_i |x_i|^p \big)^{1/p}$$

In [17]:
print(x)
print(np.linalg.norm(x))                # "normal" L2-norm
print(np.linalg.norm(x, ord=2))         # L-2 norm
print(np.linalg.norm(x, ord=1))         # L-1 norm = sum of abs values
print(np.linalg.norm(x, ord=np.inf))    # L-Inf norm = max value


[1 2 3]
3.7416573867739413
3.7416573867739413
6.0
3.0


### Transpose, Trace, Determinant, Inverse, Eigenvalues, Condition

In [18]:
print(np.matrix.transpose(A))
print(np.trace(A))
print(np.linalg.det(A))
print(np.linalg.inv(B))    # Inverse of A does not exist
L,U = np.linalg.eig(A)
print(L)
print(U)
print(np.linalg.cond(A))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
15
0.0
[[ 1.   0.  -0.5]
 [ 0.5  2.  -1.5]
 [-0.5 -1.   1. ]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
3.813147060626918e+16


In [21]:
D,P = np.linalg.eig(B)
print(np.linalg.multi_dot([P,np.diag(D),np.linalg.inv(P)]))
print(np.linalg.multi_dot([P,np.diag(D),np.linalg.inv(P)])-B)

[[2. 2. 4.]
 [1. 3. 5.]
 [2. 4. 8.]]
[[ 1.77635684e-15 -2.22044605e-16  0.00000000e+00]
 [ 1.11022302e-15 -2.22044605e-15 -3.55271368e-15]
 [ 2.22044605e-15 -8.88178420e-16 -8.88178420e-16]]


### *Solving systems of equations*

Take the system of linear equations

$$\begin{eqnarray}
2x + 3y + 4z & = & 23 \nonumber\\
2x - 1y + 2z & = & 8\nonumber\\
3x + 4y + 5z & = & 30
\end{eqnarray}$$

 This system can be written in matrix form as
$$
\begin{pmatrix}
2  &  3  &   4\\
2  & -1  &   2\\
3  &  4  &   5
\end{pmatrix}
\begin{pmatrix}
x\\
y\\
z
\end{pmatrix}
=
\begin{pmatrix}
23\\
8\\
30
\end{pmatrix}
$$

Or shorter as 
$$A x = b $$

The solution is then
$$ x = A^{-1} b$$

Now ...
* solve the system of equations using Python
* verify the result (i.e. check that $A x = b$ holds) 

In [27]:
# Python code goes here
A = np.array( [[2,3,4],[2,-1,2],[3,4,5]] )
b = np.transpose(np.array([[23,8,30]]))
Ainv = np.linalg.inv(A)
x = Ainv.dot(b)
print(x)

# check
print(A.dot(x)-b)
print( max(abs(A.dot(x)-b) / abs(A.dot(x)+b)) < 1E-8 )

[[1.5]
 [2. ]
 [3.5]]
[[3.90798505e-14]
 [2.48689958e-14]
 [5.68434189e-14]]
[ True]
